### ISSUE TITLE
Slashes not escaped when searching

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-content-app#822]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
I have a folde with following name: "myFolder 1/18" containing a slash "/".

When I search for it, the quick search shows the correct results. Once I hit enter and go to the search page I will receive an error, since the slashes are not escaped and the Angular Routing understands them as part of the URL.

When I search for it using the alfresco 

**Expected behavior:**
I should be able to search with a string containing a slash.

**Component name and version:** 
It's inside the search.effect.ts : https://github.com/Alfresco/alfresco-content-app/blob/dc9a31455ed549b76c6c125ccc6c92be6cf1ca05/src/app/store/effects/search.effects.ts#L40

**Comment by john-knowles** [comment]
Thank you for raising this issue; we've logged it into our JIRA project and will investigate in due course.

**Comment by MariusGrunenberg** [comment]
I can provide a possible fix, will create a pull request later today.

**Comment by john-knowles** [comment]
We have not started working on it yet, your contribution will be greatly appreciated!  Please create a pull request to "development" branch, thank you 👍

**Comment by DenysVuika** [comment]
@M3noetius I think the issue is not in the search calls, but redirecting to the search results page. I guess the encode/decode URI fragment is needed for the query portion not to break the routing itself, see the link in the original issue: https://github.com/Alfresco/alfresco-content-app/blob/dc9a31455ed549b76c6c125ccc6c92be6cf1ca05/src/app/store/effects/search.effects.ts#L40

I believe with 'myFolder 1/18' the url becomes `/search;q=myFolder 1/18` and `/18` is treated as a child route path.

**Comment by M3noetius** [comment]
@DenysVuika  I see what you mena.I was so fascinated about folders with forward slash ("I have a folde with following name")  that I did not focus at the rest of the issue.
 So some encoding will most probably do the trick. We will try to fix it !

**Comment by MariusGrunenberg** [comment]
@M3noetius I have created a PR, where I fixed the Encoding. So feel free to use my fix.

It has worked for me in a project

**Comment by M3noetius** [comment]
I currently trying to push a fix !
